server:
  port: 9091

spring:
  application:
    name: Product Microservice
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping
  profiles:
    active: local


logging:
  file:
    name: d:spring\logs\product.log

  logback:
    rollingpolicy:
      max-file-size: 50KB


product:
    currencies:
      - EGP
      - USD
      - EUR