server:
  port: 8081


spring:
  mail:
    host: smtp.mailtrap.io
    port: 465
    username: 6cfb505a2240e2
    password: 0b8566f7b06a2a
    test-connection: true
  boot:
    admin:
      ui:
        login-icon: 'assets/img/logo.png'
        available-languages:
          - en
          - fr
        view-settings:
          - name: 'about'
            enabled: false
        brand: "<img src='assets/img/logo.png'><span> Mehisen Services</span>"
        title: "Mehisen Services for Online Shopping"
      notify:
        mail:
          to: bevide4439@lance7.com
          ignore-changes:
            - ''

